### ISSUE TITLE
Rename the project to Decentralized Identity Interop Profile

### ISSUE THREAD

**Issue by cre8** [DutchBlockchainCoalition/DIIP#8]
The new name seems to be `Decentralized Identity Interop Profile`, so it would be good to rename the project to DIIP. According to this [link](https://github.com/orgs/community/discussions/22669) there should be a automated redirect

**Comment by nklomp** [comment]
Thanks, indeed the project will be renamed over here as well. 

@Oskar-van-Deventer @maaikevanleuken. Do you have admin rights on this repo. If so could you make this change, or better yet make me admin. Not entirely sure what Alexanders' Github handle is.

**Comment by nklomp** [comment]
This has been done a long time ago. Thanks for bringing it up
